packages:
  - '.'
  - 'packages/11ty.ts'
  - 'packages/eleventy-plugin-html-terser'
  - 'packages/eleventy-plugin-svg-sprite'
  - 'packages/eleventy-plugin-markdown'
  - 'packages/eleventy-plugin-json-fusion'
  - 'packages/e11ty'