packages:
  - '.'
  - 'plugins/11ty.ts'
  - 'plugins/eleventy-plugin-html-terser'
  - 'plugins/eleventy-plugin-svg-sprite'
  - 'plugins/eleventy-plugin-markdown'
  - 'plugins/eleventy-plugin-json-fuse'
  - 'package/e11ty'